### ISSUE TITLE
Extended Tab Titles

### ISSUE THREAD

**Issue by csm10495** [yacir/markdown-fenced-code-tabs#1]
Hi,

This is a great extension, though my team is using it in a slightly different way than intended. We are using it on multiple documentation pages via mkdocs and using the code tabs as different versions of implementation details of code. So instead of putting a language after the ```, we put a version like 1_0 and so on. This way we can have lots of versions shown via different tabs. By doing this, we lose the ability to specify a language  and we can't use period characters in the title. Is it possible to allow us to specify the string for the tab including the period character?

For example:

'''1.0
code
'''
'''2.0
code
'''

So that when rendered by mkdocs, we get 2 tabs (one titled 1.0 and one titled 2.0). This works similarly right now if I do (except with underscores):
'''1_0
code
'''
'''2_0
code
'''

What about something more complex like:

'''"1.0 A"
code
'''
'''"2.0 B"
code
'''

It would be great if this could make tabs with "1.0 A" and "2.0 B" as denoted by the quoted string past the ```.

Note that I've used ' instead of ` for the examples to prevent GitHub formatting the markdown.

Thanks again for the extension!

**Comment by csm10495** [comment]
I just played with this a bit more. Looks like you can put a string with dots in {} after the `. I guess we can just say that this issue is asking for that to be more clearly documented in addition to if there is a way to use spaces

**Comment by csm10495** [comment]
Actually, I'm wrong yet again. It looks like it works, though when clicking on the second tab, the data from the first is still shown as long as there is a period in the title. So there is still an issue there as well.

**Comment by yacir** [comment]
@csm10495 i think it could great to add a new option te set a custom title without loosing the the ability to specify a language. Something like : 

```
    ```curl fct_title="1.0 A"
    $ curl -O wget http://example.com/pk.zip
    ```
```

**Comment by yacir** [comment]
@csm10495 check the 0.2.0 ;)

**Comment by csm10495** [comment]
Cool beans... though I think you may mean

```curl fct_label="1.0 A"
    $ curl -O wget http://example.com/pk.zip
```

took me a sec, but realized its fct_label instead of fct_title.
