### ISSUE TITLE
Can't switch to non-active tab

### ISSUE THREAD

**Issue by otisg** [yacir/markdown-fenced-code-tabs#11]
Trying to use this extension simply for the tabs, not necessarily because I want to combine it with code highlighting.  Not sure if that matters, but thought I'd mention it.  I should also mention I'm using the Material theme.

This is what I have:
\`\`\`redhat fct_label="RedHat"
something about redhat
\`\`\`
\`\`\`centos fct_label="CentOS"
something about centos
\`\`\`

I'm seeing the tabs and they seem to have correctly generated links with anchor tags like:
https://....page#tab-0-redhat
https://....page#tab-0-centos

But when I click on a non-active tab it doesn't become active.  I've looked at the generated HTML and it looks good:

                <div class="code-nav-container">

        <ul class="nav nav-tabs">
        <li class="nav-item active">
            <a href="#tab-0-redhat" aria-controls="tab-0-redhat" role="tab" data-toggle="tab" data-lang="redhat">RedHat</a>
        </li>

        <li class="nav-item ">
            <a href="#tab-0-centos" aria-controls="tab-0-centos" role="tab" data-toggle="tab" data-lang="centos">CentOS</a>
        </li>
        </ul>

        <div class="tab-content">

        <div role="tabpanel" class="tab-pane active" id="tab-0-redhat">
            <div class="codehilite"><pre><span></span>something about redhat</pre></div>
        </div>
        <div role="tabpanel" class="tab-pane " id="tab-0-centos">
            <div class="codehilite"><pre><span></span>something about centos</pre></div>
        </div>
        </div>
                </div>

Am I doing something wrong?

**Comment by yacir** [comment]
it seems like the #10 issue. i should add it to the doc 😅

**Comment by yacir** [comment]
Agree with you, the best solution is to include it. I'll try to work on it this week end :).

**Comment by yacir** [comment]
@otisg now with the new version the `default` template needs only CSS to works. 
take a look to the new docs :).

I ll close this issue :)
