### ISSUE TITLE
Help with setting up CSS or HTML files to make tabs work with material

### ISSUE THREAD

**Issue by lmtisme** [yacir/markdown-fenced-code-tabs#15]
I commented in a closed issue so I thought I would create a new one to ask for some help.  

I am a newbie to using Mkdocs and I was told it was simple as adding
``` android tab="Android"
    blah blah
```
```ios tab="iOS"
  yada yada
```
to make tabs work.  Never that simple ;-)  Note the above has three backticks then android followed by tab="Tabname", then it is duplicated for iOS .

I downloaded markdown-fenced-code-tabs and realize I need to add some CSS or Javascript code but I don't know where.   Any help or advice is appreciated.  I am not a developer but a documentation person at a new job.

**Comment by yacir** [comment]
Hello @lmtisme! Could you upload the content of your `mkdocs.yml` ?

**Comment by lmtisme** [comment]
Good day Yassir!  I did not include the pages as that is the boring stuff. From what I have been reading, the 'material' theme is problematic with tabs.

# Theme directory
theme:
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'cyan'
  favicon: 'images/favicon.ico'
  logo: 'images/SAP_scrn_R.png'
#theme: 'material'
#theme_dir: 'docs/theme'
    
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc(permalink=true)
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.superfences

use_directory_urls: false

# Page tree
pages:

**Comment by lmtisme** [comment]
I found out what my problem was.  My mkdocs-material was out of date. I had to do a force reinstall of 2.9.2 and first word after the backticks is the language name.
