### ISSUE TITLE
Sorted - Can't get tabs to display

### ISSUE THREAD

**Issue by emh1908** [yacir/markdown-fenced-code-tabs#9]
HI .. I'm far from an mkdocs expert and not a programmer either! I just about know enough to do my documentation.  I'd like to implement these code tabs but I can't get them to display correctly. I've probably missed something, so I'd be really grateful for your assistance. I'm using material theme. I've copied the code-tab.css as you suggested in another query.  This is in my mkdocs.yml:

#Extensions
markdown_extensions:
    - extra
    - toc
    - nl2br
    - codehilite(css_class=highlight,use_pygments=True)
    - admonition
    - markdown_fenced_code_tabs:
        single_block_as_tab: True
        
extra_css:
    - css/extra.css
    - css/highlight-fix.css
    - css/pygments-custom.css
    - code-tabs.css

Thank you so much in advance.

![code tabs example](https://user-images.githubusercontent.com/36504760/36255829-6a1f5834-1248-11e8-91a9-19f3f0f37d07.png)

**Comment by emh1908** [comment]
Sorted . formatting errors!

**Comment by otisg** [comment]
I'm seeing the same thing and can't find any issues with my MD formatting, but I see the output with 2 bullet points on top just like you.  How did you end up fixing this?  Thanks.

**Comment by emh1908** [comment]
Hi

This is what one of my Dev guys suggested and it worked (I'm a tech author not a developer :) ! 

1.   Edit your mkdocs.yml file and add this at the bottom :
 
     extra_javascript:
           -  'javascripts/jquery-3.3.1.min.js'
           -  'javascripts/bootstrap.min.js'

   (The order of the files in the extra_javascript option is important).

2.   Create a directory "javascripts" under your /docs directory and copy the two files from these links into that directory. 
      
      https://code.jquery.com/jquery-3.3.1.min.js 

      https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js 



Hopefully this will sort it for you.

Regards, Elaine
            





On Apr 20, 2018, at 08:59 PM, Otis Gospodnetić <notifications@github.com> wrote:

I'm seeing the same thing and can't find any issues with my MD formatting, but I see the output with 2 bullet points on top just like you. How did you end up fixing this? Thanks.
